import type { Metadata } from "next";
import { LegalLayout, LegalSection } from "@/components/layout/LegalLayout";

export const metadata: Metadata = {
  title: "Privacy policy",
  description: "What we collect, why, and how you can control it.",
};

export default function PrivacyPage() {
  return (
    <LegalLayout
      title="Privacy policy"
      description="What we collect, why, and how you can control it."
      lastUpdated="August 19, 2026"
    >
      <LegalSection heading="1. Overview">
        <p>
          This policy explains what personal data Impostor collects, how it&apos;s used, and the choices you have.
          We aim to collect the minimum needed to run the game: accounts, matches, and the leaderboard.
        </p>
      </LegalSection>

      <LegalSection heading="2. What we collect">
        <p>
          <strong className="text-foreground">Account data.</strong> Email address, a hashed password, your chosen
          username, avatar color, and any avatar photo you upload.
        </p>
        <p>
          <strong className="text-foreground">Game data.</strong> Rooms you join or host, clues and votes you submit
          during a round, chat messages sent in a room, and aggregate stats (games played, wins, and similar counts)
          shown on your profile and the public leaderboard.
        </p>
        <p>
          <strong className="text-foreground">Billing data.</strong> If you subscribe to premium, Stripe processes
          the payment and shares back a customer ID and subscription status. We don&apos;t receive or store your card
          number.
        </p>
        <p>
          <strong className="text-foreground">Technical data.</strong> Standard request logs (IP address, browser
          type, timestamps) generated by our hosting and database providers for security and debugging. If your first
          visit includes campaign parameters in the URL (utm_source and similar), we store those locally in your
          browser so we can tell which channels bring players back; that data never leaves your device unless you
          sign up, in which case it may accompany your account creation.
        </p>
      </LegalSection>

      <LegalSection heading="3. What we don't do">
        <p>
          We don&apos;t sell your personal data. We don&apos;t run third-party ad trackers. We don&apos;t use your
          gameplay content to train models. The only outside processors involved are the ones needed to run the
          service: Supabase (database, authentication, file storage) and Stripe (payments).
        </p>
      </LegalSection>

      <LegalSection heading="4. How we use your data">
        <p>
          To create and secure your account, run matches in real time, calculate and display stats and leaderboard
          rankings, process premium subscriptions, respond to support requests submitted through the contact form,
          and keep the service reasonably secure against abuse.
        </p>
      </LegalSection>

      <LegalSection heading="5. Cookies and local storage">
        <p>
          We use a small number of essential cookies to keep you signed in. We also use your browser&apos;s local
          storage for non-essential preferences, like your theme choice, whether you&apos;ve dismissed the cookie
          notice, and first-touch campaign attribution. See the{" "}
          <a href="/cookies" className="font-semibold text-foreground underline underline-offset-2">
            cookie policy
          </a>{" "}
          for the full list.
        </p>
      </LegalSection>

      <LegalSection heading="6. Data retention">
        <p>
          We keep account and stats data for as long as your account exists. Guest accounts and the rooms they leave
          behind are cleaned up automatically after a period of inactivity. Chat messages live for the lifetime of
          the room. If you delete your account, we remove your profile, avatar, and personal identifiers within a
          reasonable time, though aggregate/anonymized statistics may be retained.
        </p>
      </LegalSection>

      <LegalSection heading="7. Your rights">
        <p>
          Depending on where you live, you may have the right to access, correct, export, or delete your personal
          data, and to object to certain processing. You can update your username, avatar, bio, and pronouns anytime
          from your{" "}
          <a href="/profile" className="font-semibold text-foreground underline underline-offset-2">
            profile page
          </a>
          . For account deletion or a data export, reach out through the{" "}
          <a href="/contact" className="font-semibold text-foreground underline underline-offset-2">
            contact page
          </a>
          .
        </p>
      </LegalSection>

      <LegalSection heading="8. Children">
        <p>
          Impostor isn&apos;t directed at children under 13, and we don&apos;t knowingly collect personal data from
          them. If you believe a child has created an account, contact us and we&apos;ll remove it.
        </p>
      </LegalSection>

      <LegalSection heading="9. Changes to this policy">
        <p>
          If we materially change how we handle your data, we&apos;ll update the date at the top of this page and, for
          significant changes, let signed-in users know in the app.
        </p>
      </LegalSection>

      <LegalSection heading="10. Contact">
        <p>
          Privacy questions or requests go to the same place as everything else: the{" "}
          <a href="/contact" className="font-semibold text-foreground underline underline-offset-2">
            contact page
          </a>
          .
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
